### ISSUE TITLE
Examples fail on Ubuntu 18.04

### ISSUE THREAD

**Issue by DeltaF1** [life4/homoglyphs#16]
The first `to_ascii` example from the readme fails on ubuntu 18, python 3.6.7. The expected output is `['tect']`, but it just returns `[]`

**Comment by orsinium** [comment]
Hm. By some reason, `т` -> `t` mapping now not in the list of confusables.

```bash
curl ftp://ftp.unicode.org/Public/security/latest/confusables.txt | grep -F 'т'
```

They decided that this head of `t` is valuable. I'll update the docs.
