### ISSUE TITLE
Is there a way to compare a string with another string that may have homoglyphs or visually similar characters in it

### ISSUE THREAD

**Issue by DavidRBailey** [life4/homoglyphs#18]
Is there a way, using this library, to compare a string with another string that may have homoglyphs or visually similar characters in it.

"quotes" ~= “quotes” : same (similar characters)
MacBride ~= McBride : different (obviously)
McBride ~= McBr𝗂de . : same (unicode homoglyph swap)

If not, then consider this a feature request. :-)

**Comment by orsinium** [comment]
It depends on what you want. [to_ascii](https://github.com/life4/homoglyphs#converting-glyphs-to-ascii-chars) should fit for most of the cases. For glyphs in non-latin words use [get_combinations](https://github.com/life4/homoglyphs#homoglyphs-1) and compare results as sets.
