### ISSUE TITLE
Repo comparison in the ReadMe

### ISSUE THREAD

**Issue by DonaldTsang** [life4/homoglyphs#19]
Compare this repo with...
- https://github.com/codebox/homoglyph
- https://github.com/vhf/confusable_homoglyphs
- https://github.com/DavidJacobson/SafeText
- https://github.com/NebulousLabs/glyphcheck
What is unique about this repo when compared to the others? Is it possible to make a table?

**Comment by DonaldTsang** [comment]
Also slightly less related:
- https://github.com/adam-lynch/olc (fuzzer)
- https://github.com/nodeca/unhomoglyph (removal)
- https://github.com/DissectMalware/PySameSame (generator)
- https://github.com/Zenithar/go-typogenerator (complex fuzzer/generator)

**Comment by orsinium** [comment]
1. js
2. Already compared
3. cli tool, not lib
4. go

That was easy

**Comment by DonaldTsang** [comment]
@orsinium I am referring to feature sets of such repos, not necessarily the language.
