### ISSUE TITLE
Language-sensitive Homoglyph removal

### ISSUE THREAD

**Issue by DonaldTsang** [life4/homoglyphs#20]
Is it possible to have homoglyph removal that does not remove language-specific characters?
For example Germanic ÄÖÜßÆØÅ (and icelandic ÐÞÁÉÍÓÚÝ) or Romance language's ÁÉÍÓÚÝÂÊÎÔÛÀÈÙËÏÜŸÃÑÕÇ (and Romanian ĂÂÎȘȚ)
Ideas:
1. Some diacritics do look similar (e.g. Circumflex vs Inverted Breve, Caron vs Breve, Diaeresis vs Double acute/grave, Tilde vs Macron, Overdot vs Overring)
2. It is very hard to remove homoglyphs of diacritics-based characters as some characters won't be combined in the NFC formalization process, which require conversion before NFC

For more language references https://github.com/Ousret/charset_normalizer/issues/26

**Comment by orsinium** [comment]
Just specify alphabet, category, or language, and strategy. That's the main feature of the lib, you have full control of the alphabet, do what you want.
